### ISSUE TITLE
deployment

### ISSUE THREAD

**Issue by kylemac** [carrot/burrow#27]
we should have a default deployment strategy.

**Comment by BrandonRomano** [comment]
I'm kinda in a weird point with this issue, because apparently go is coming out with their own package manager in their next release and I want wait for that to come out before I make any changes.

Right now, deploying requires us to change our dependency manager (which I am not particularly the biggest fan of).  Am hoping that the new dependency manager that comes out will resolve this and make it very simple to document

**Comment by BrandonRomano** [comment]
Setting this as blocked until the next version of Go comes out

**Comment by BrandonRomano** [comment]
Will be resolved in #39... Will come with an AWS Beanstalk deployment strategy
